# Generated by Django 3.1.7 on 2021-03-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='description',
            new_name='paradigm',
        ),
        migrations.RemoveField(
            model_name='language',
            name='published',
        ),
    ]
