# Generated by Django 3.1.7 on 2021-03-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20210327_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pogrammer',
            new_name='Programmer',
        ),
    ]
